# Скорость и память сборки
org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Папка plugins вашего сервера для задачи `./gradlew deploy`
# (укажите свой путь, например: pluginsDir=C:/servers/folia/plugins)
pluginsDir=server/plugins

# Версия плагина (её видит plugin.yml и имя JAR). Можно переопределить при сборке: -Pversion=1.7.0
version=1.6.5
